service: qi-spring-serverless-demo

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  memorySize: 4096
  timeout: 60
  region: ${opt:region, self:custom.defaultRegion}
  environment: ${file(./src/config/env.yml):${opt:stage, self:custom.defaults.stage}}
  iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:*
          - "ssm:GetParameters"
        Resource: "*"
custom:
  defaultRegion: us-east-2
  stage: ${opt:stage}
  defaults:
    stage: qa

plugins:
 - serverless-offline
 
package:
  artifact: build/distributions/spring-serverless-demo.zip

functions:
  archiveAudit:
    handler: com.pearson.central.audit.ArchiveAudit
    events:
      - schedule:
          rate: rate(60 minutes)